module.exports = {
  symbol: null,
  name: null,
  totalSupply: null,
  decimals: null,
  hre: null,
  expect: null,
  delay: null,
  accounts: {
    a: { MyGovernor: null },
    b: { MyGovernor: null },
    c: { MyGovernor: null },
  },
  contracts: { MyGovernor: null },
  ipfsUrl: null,
  voteStart: null,
  voteEnd1: null,
  voteEnd2: null,
  location1: null,
  location2: null,
  location3: null,
  setting: null,
};
